-- MySQL Script generated by MySQL Workbench
-- Tue May 26 10:26:28 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema comercial
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema comercial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `comercial` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `comercial` ;

-- -----------------------------------------------------
-- Table `comercial`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comercial`.`categorias` (
  `product_category_name` VARCHAR(100) NULL DEFAULT NULL,
  `product_category_name_english` VARCHAR(100) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `comercial`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comercial`.`clientes` (
  `customer_id` VARCHAR(50) NULL DEFAULT NULL,
  `customer_city` VARCHAR(50) NULL DEFAULT NULL,
  `customer_state` VARCHAR(10) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `comercial`.`itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comercial`.`itens` (
  `order_id` VARCHAR(50) NULL DEFAULT NULL,
  `product_id` VARCHAR(50) NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `comercial`.`pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comercial`.`pagamentos` (
  `order_id` VARCHAR(50) NULL DEFAULT NULL,
  `payment_type` VARCHAR(20) NULL DEFAULT NULL,
  `payment_value` FLOAT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `comercial`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comercial`.`pedidos` (
  `order_id` VARCHAR(50) NULL DEFAULT NULL,
  `customer_id` VARCHAR(50) NULL DEFAULT NULL,
  `order_status` VARCHAR(20) NULL DEFAULT NULL,
  `order_purchase_timestamp` DATETIME NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `comercial`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comercial`.`produtos` (
  `product_id` VARCHAR(50) NULL DEFAULT NULL,
  `product_category_name` VARCHAR(100) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
